apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}